#!/bin/sh
# Setup a machine for Sublime Text 3
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup.$(date +"%Y-%m-%d %H:%M")"
rm -rf "$sublime_dir/User"
cp -R $DOTFILES/sublime3/User ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

# Grab the Soda theme
cd "$sublime_dir"
git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
